### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by Lucas-Erkana** [Lucash2022/Tasty-Bites#13]
![Hi Reviewer](https://github.com/Lucash2022/Tasty-Bites/assets/41428579/5499c981-2bbc-4e93-8aed-fc33af7059d4)

We are 2 on this team @Lucash2022 (TM1) and @byiringiroscar (TM2):
Here is a link to the [Kanban board](https://github.com/users/Lucash2022/projects/4/views/1)
Here is a link to the [repo ](https://github.com/Lucash2022/Tasty-Bites)

**Comment by Ismailco** [comment]
Hi @Lucash2022, @byiringiroscar, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that may not have a Kanban board linked to it, when I click on the link in the issue description I got redirected to a 404 page

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Lucas-Erkana** [comment]
Hi @Ismailco 
Apologies for that we forgot to make it public. I have rectified it now.

**Comment by Lucash2022** [comment]
Hi @Ismailco 
Apologies for that we forgot to make it public.

**Comment by ichala** [comment]
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Tasks equally distributed  ✔️ 
- Tasks have details ✔️ 
- Kanban is ready good luck ✔️


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
